- .github/workflows/bundlewatch.yml
- .github/workflows/test-PR.yml
- package-lock.json
- package.json
> Add bundlewatch

- package.json
- utils/env.ts
> Add build:vercel

- components/headers/ctaHeader/CtaHeader.tsx
- components/layout/AppSpinner.tsx
- components/layout/Layout.tsx
- components/loginForm/LoginForm.tsx
- next.config.js
- package-lock.json
- package.json
- pages/_app.tsx
- pages/admin.tsx
- pages/login.tsx
- pages/questions/[technology].tsx
- pages/questions/index.tsx
- pages/questions/p/[id].tsx
- redux/actions.ts
- redux/reducers/index.ts
- redux/reducers/oneQuestion.ts
- redux/reducers/questions.ts
- redux/reducers/routeDetails.ts
- redux/store.ts
- utils/analytics.ts
- utils/redirect.ts
- utils/types.ts
> Issue-8: Update next-redux-wrapper

- app.js
- components/questions/allQuestions/AllQuestions.tsx
- components/questions/allQuestions/allQuestionsFooter/AllQuestionsFooter.tsx
- components/questions/allQuestions/allQuestionsHeader/AllQuestionsHeader.tsx
- components/questions/mobileActionButtons/MobileActionButtons.tsx
- components/questions/questionsList/QuestionsList.tsx
- components/questions/questionsList/questionItem/QuestionItem.tsx
- components/questions/questionsSidebar/QuestionsSidebar.tsx
- components/questions/questionsSidebar/levelFilter/LevelFilter.tsx
- components/questions/questionsSidebar/technologyFilter/TechnologyFilter.tsx
- components/questions/selectedQuestions/SelectedQuestions.tsx
> Rewrite classes 3

- scripts/ssh-script-deploy.sh
> Build script for API and WWW

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- apps/api/src/server.ts
> Add contributing

- apps/www/package.json
- apps/www/pages/_app.tsx
- apps/www/pages/questions/[technology].tsx
- apps/www/redux/actions.ts
- apps/www/redux/reducers/index.ts
- apps/www/redux/store.ts
- apps/www/utils/hooks.tsx
- yarn.lock
> Temp. Fix pagination

- apps/app/app/globals.css
- apps/app/app/layout.tsx
- apps/app/package.json
- apps/app/postcss.config.js
- apps/app/tailwind.config.js
- pnpm-lock.yaml
> feat: setup tailwind

- apps/app/src/app/layout.tsx
- apps/app/src/components/Header/ActiveNagivationLink.tsx
- apps/app/src/components/Header/Header.tsx
- apps/app/src/components/Header/HeaderNavigation.tsx
> feat(app): add hamburger button

- apps/api/modules/questions/questions.routes.ts
- apps/api/modules/questions/questions.schemas.ts
- packages/openapi-types/types.ts
> feat(api): add questions voting

- apps/api/modules/questions/questions.params.ts
- apps/api/modules/questions/questions.routes.ts
- apps/api/modules/questions/questions.schemas.ts
- packages/openapi-types/types.ts
> feat(api): add endpoint to get votes

- apps/api/modules/questions/questions.params.ts
- apps/app/src/app/(main-layout)/questions/[technology]/[page]/page.tsx
- apps/app/src/components/QuestionItem/QuestionItem.stories.ts
- apps/app/src/components/QuestionItem/QuestionItem.tsx
- apps/app/src/components/QuestionItem/QuestionVoting.tsx
- apps/app/src/hooks/useDevFAQRouter.ts
- apps/app/src/hooks/useGetQuestionVotes.ts
- apps/app/src/hooks/useQuestionVoting.ts
- apps/app/src/services/questions.service.ts
- apps/app/src/types.ts
> feat(app): add questions voting

- CONTRIBUTING.md
Rozszerzenie instrukcji zawartych w pliku `CONTRIBUTING.md` o wzmiankę na temat zmiennych środowiskowych.
> Extend contributing instructions

- apps/app/src/components/Button/Button.tsx
- apps/app/src/components/CloseButton/CloseButton.tsx
- apps/app/src/components/Select/Select.tsx
> fix(app): fix contrast ratio issues and more

- apps/app/src/app/(main-layout)/authors/page.tsx
- apps/app/src/components/Author/Author.tsx
- apps/app/src/components/Footer.tsx
- apps/app/src/components/QuestionsHeader.tsx
- apps/app/src/components/Select/Select.tsx
This PR:
- centers verticaly all elements which `QuestionsHeader` contains,
- change grid template on the `authors` page to achieve better ux experience on mobile devices,
- adjust author box height to match the highest of them in the same row,
- make main `footer` more responsive / flexible,
- add box-shadow to default `Select` component.
> fix(app): Frontend fixes

- apps/app/src/app/(main-layout)/questions/layout.tsx
- apps/app/src/components/QuestionsSidebar/LevelFilter/LevelFilter.tsx
- apps/app/src/components/QuestionsSidebar/QuestionsSidebar.tsx
- apps/app/src/components/QuestionsSidebar/QuestionsSidebarSection.tsx
- apps/app/src/components/QuestionsSidebar/TechnologyFilter/TechnologyFilter.tsx
- apps/app/src/styles/tailwind.css
- apps/app/tailwind.config.js
This PR fixes #462 issue. Changes:
- change an aside divider from solution which based on shadows to border with gradient,
- adjust width of a sidebar, adjust demensions of links and gaps inside lists in each section inner sidebar,
- add ability to scroll sidebar when it does not fit whole on height of the viewport,
> fix(app): fix sidebar

- apps/app/src/app/(main-layout)/layout.tsx
- apps/app/src/app/(main-layout)/questions/layout.tsx
- apps/app/src/components/Container.tsx
- apps/app/src/components/SkipToTheContent.tsx
- apps/app/src/components/StaticPageContainer.tsx
PR improve accessibility by adding skip to the content link.
> feat(app): add skip to the content link

- apps/app/src/components/AddQuestionConfirmationModal.tsx
- apps/app/src/components/AddQuestionModal.tsx
- apps/app/src/components/AppModals.tsx
- apps/app/src/components/BaseModal/BaseModal.tsx
- apps/app/src/components/BaseModal/ModalTitle.tsx
- dodanie dodatkowych artybutów `aria-*` do modala,
- dodanie tytułu do modala potwierdzającego dodanie pytania (`AddQuestionConfirmationModal`)
Motywacja do wprowadzenia zmian:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal
- https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/#name_calculation
> fix(app): improve modal a11y

- .vscode/settings.json
- apps/api/modules/answers/answers.mapper.ts
- apps/api/modules/answers/answers.routes.ts
- apps/api/modules/answers/answers.schemas.ts
- apps/api/prisma/migrations/20230106153310_add_question_answers_votes/migration.sql
- apps/api/prisma/schema.prisma
> feat(api): add question answers likes and dislikes

- apps/app/src/components/BaseModal/BaseModal.tsx
> feat(app): close modal on press Escape key

- apps/app/src/components/AdminPanel/AdminPanelQuestionLeftSection.tsx
- apps/app/src/components/UserQuestions/UserQuestionLeftSection.tsx
> fix(app): fix styles in admin and user panel

- apps/app/src/components/BaseModal/BaseModal.tsx
- apps/app/src/components/Header/UserMenu.tsx
- apps/app/src/hooks/useOnKeydown.ts
- apps/app/src/hooks/useOnPressKey.ts
- Add new hook 'useOnPressKey'.
- Refactor code in 'BaseModal' to implement newly created hook.
> feat(app): new hook 'useOnKeydown'; implement new hook in 'BaseModal'
